import { useCallback, useEffect, useRef, useState } from "react";
import { METHOD, dgmsThreshold, outOfRange } from "../../lib/api";
import type { ModelMetrics, Prediction, Sensitivity } from "../../lib/api";
import type { ModeId } from "../../data/modes";
import { fieldsFor } from "../../data/analysisConfig";

export type RunState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "done";
      prediction: Prediction;
      at: Date;
      params: Record<string, number>;
    };

/** Sensitivity is measured separately — each probe is a full model inference. */
export type SensState =
  | { status: "idle"; probes: number; etaSec: number }
  | { status: "running"; done: number; total: number }
  | { status: "done"; items: Sensitivity[] };

const GREEN = "#30d158";
const AMBER = "#ff9f0a";
const RED = "#ff453a";

function verdictColor(fos: number, threshold: number) {
  if (fos >= threshold) return GREEN;
  if (fos >= threshold * 0.9) return AMBER;
  return RED;
}

function Row({ label, value, muted = false }: { label: string; value: React.ReactNode; muted?: boolean }) {
  return (
    <div className="flex items-baseline justify-between gap-4 border-b border-white/6 py-1 last:border-b-0">
      <span className="text-[12px] text-white/45">{label}</span>
      <span className={`text-[12.5px] tabular-nums ${muted ? "text-white/30" : "text-white/85"}`}>{value}</span>
    </div>
  );
}

function Skeleton() {
  return (
    <div className="p-5">
      <p className="mb-4 text-[12.5px] text-white/45">Running prediction…</p>
      <div className="animate-pulse space-y-4">
        <div className="h-12 w-40 rounded-lg bg-white/8" />
        <div className="h-3 w-64 rounded bg-white/6" />
        <div className="grid grid-cols-2 gap-3 pt-2">
          <div className="h-24 rounded-xl bg-white/5" />
          <div className="h-24 rounded-xl bg-white/5" />
        </div>
        <div className="h-3 w-48 rounded bg-white/6" />
      </div>
    </div>
  );
}

function Disclaimer() {
  return (
    <div className="flex shrink-0 items-start gap-2 border-t border-white/[0.07] bg-white/[0.03] px-4 py-2 backdrop-blur-md">
      <svg width="13" height="13" viewBox="0 0 16 16" className="mt-[2px] shrink-0" aria-hidden>
        <circle cx="8" cy="8" r="7" fill="none" stroke="rgba(255,255,255,0.4)" strokeWidth="1.2" />
        <rect x="7.3" y="6.6" width="1.4" height="5" rx="0.7" fill="rgba(255,255,255,0.55)" />
        <circle cx="8" cy="4.6" r="0.85" fill="rgba(255,255,255,0.55)" />
      </svg>
      <p className="text-[10.5px] leading-[1.5] text-white/40">
        These results are generated by a machine-learning model and may contain errors. They must not be
        relied upon as the sole basis for slope design or operational decisions. All outputs require
        verification by a competent person against site-specific ground investigation data and the
        applicable DGMS regulations before use.
      </p>
    </div>
  );
}

/** Human label for a field key, from the mode config. */
function labelFor(mode: ModeId, key: string): string {
  return fieldsFor(mode).find((f) => f.key === key)?.label ?? key;
}

/**
 * Above this panel width the results split into two columns; below it — a
 * tablet-ish viewport, or the panel dragged narrow — everything stacks so
 * nothing gets crushed.
 */
const TWO_COL_MIN_W = 820;

/**
 * Tracks an element's width so content can reflow to the space it has.
 *
 * Uses a CALLBACK ref, not a ref object + mount effect: the measured element
 * only exists in the "done" branch, so an effect running at mount (while the
 * panel is idle) would find nothing and never re-attach.
 */
function useWidth<T extends HTMLElement>() {
  const [w, setW] = useState(0);
  const obs = useRef<ResizeObserver | null>(null);

  const ref = useCallback((node: T | null) => {
    obs.current?.disconnect();
    obs.current = null;
    if (!node) return;
    const ro = new ResizeObserver(([entry]) => setW(entry.contentRect.width));
    ro.observe(node);
    obs.current = ro;
    setW(node.getBoundingClientRect().width);
  }, []);

  useEffect(() => () => obs.current?.disconnect(), []);

  return [ref, w] as const;
}

export default function ResultsPanel({
  mode,
  state,
  sens,
  metrics,
  onRerun,
  onMeasureSensitivity,
}: {
  mode: ModeId;
  state: RunState;
  sens: SensState;
  metrics: ModelMetrics | null;
  onRerun: () => void;
  onMeasureSensitivity: () => void;
}) {
  const [copied, setCopied] = useState(false);
  // measured before any early return — hook order must stay stable
  const [scrollRef, panelW] = useWidth<HTMLDivElement>();
  const twoCol = panelW >= TWO_COL_MIN_W;
  const meta = METHOD[mode];
  const dgms = dgmsThreshold(mode);

  function reportText(): string {
    if (state.status !== "done") return "";
    const lines: string[] = [
      `Slope Stability AI — ${mode} failure analysis`,
      `Generated: ${state.at.toISOString()}`,
      ``,
      `Method: ${meta.method}`,
      `Model:  ${meta.model}`,
      `Data:   ${meta.data}`,
      ``,
      `INPUTS`,
      ...Object.entries(state.params).map(([k, v]) => `  ${k} = ${v}`),
      ``,
      `RESULT`,
    ];
    if (state.prediction.kind === "fos") {
      const fos = state.prediction.fos;
      lines.push(`  Predicted FoS: ${fos.toFixed(3)}`);
      lines.push(`  DGMS minimum (${dgms.material}): ${dgms.value}`);
      lines.push(`  Assessment: ${fos >= dgms.value ? "PASSES" : "BELOW THRESHOLD"}`);
    } else {
      lines.push(`  Classification: ${state.prediction.label}`);
      lines.push(`  Failure probability: ${(state.prediction.failureProbability * 100).toFixed(1)}%`);
    }
    if (sens.status === "done") {
      lines.push(``, `SENSITIVITY (model response, one-at-a-time)`);
      sens.items.forEach((s) =>
        lines.push(`  ${s.label}: ${s.direction === "up" ? "increases" : s.direction === "down" ? "decreases" : "no effect on"} the result`)
      );
    }
    lines.push(
      ``,
      `DISCLAIMER: Model-generated output. May contain errors. Not to be relied upon as the sole`,
      `basis for slope design or operational decisions. Verify against site-specific data and DGMS`,
      `regulations before use.`
    );
    return lines.join("\n");
  }

  async function copy() {
    await navigator.clipboard.writeText(reportText());
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  }

  function exportReport() {
    const blob = new Blob([reportText()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `slope-stability-${mode}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /* ---------- non-result states ---------- */
  if (state.status === "idle") {
    return (
      <div className="flex h-full flex-col">
        <div className="flex flex-1 items-center justify-center px-6">
          <p className="max-w-sm text-center text-[13px] text-white/28">
            Set your parameters and run the prediction to see the factor of safety, model
            accuracy and interpretation.
          </p>
        </div>
        <Disclaimer />
      </div>
    );
  }

  if (state.status === "loading") {
    return (
      <div className="flex h-full flex-col">
        <div className="flex-1 overflow-hidden">
          <Skeleton />
        </div>
        <Disclaimer />
      </div>
    );
  }

  if (state.status === "error") {
    return (
      <div className="flex h-full flex-col">
        <div className="flex flex-1 flex-col items-center justify-center gap-3 px-6 text-center">
          <p className="text-[13px] text-[#ff6b5e]">{state.message}</p>
          <p className="text-[11.5px] text-white/35">
            The solver API must be running at <code>localhost:8000</code>.
          </p>
          <button
            type="button"
            onClick={onRerun}
            className="rounded-lg border border-white/16 px-3 py-1.5 text-[12px] text-white/75 hover:border-white/32"
          >
            Retry
          </button>
        </div>
        <Disclaimer />
      </div>
    );
  }

  /* ---------- results ---------- */
  const pred = state.prediction;
  const isFos = pred.kind === "fos";
  const fos = isFos ? pred.fos : null;
  const color = isFos ? verdictColor(pred.fos, dgms.value) : pred.failureProbability > 0.5 ? RED : GREEN;
  const passes = isFos ? pred.fos >= dgms.value : pred.label !== "UNSTABLE";

  return (
    <div className="flex h-full flex-col">
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-2.5">
        {/* headline — full width across the top */}
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            {isFos ? (
              <>
                <div className="flex items-baseline gap-2.5">
                  <span className="text-[38px] font-semibold leading-none tabular-nums" style={{ color }}>
                    {fos!.toFixed(2)}
                  </span>
                  <span className="text-[13px] text-white/45">Factor of Safety</span>
                </div>
                <p className="mt-1.5 text-[12.5px] text-white/55">
                  DGMS minimum for {dgms.material}: <span className="text-white/80">{dgms.value.toFixed(1)}</span> —{" "}
                  <span style={{ color }}>{passes ? "slope passes" : "below threshold"}</span>
                </p>
              </>
            ) : (
              <>
                <div className="flex items-baseline gap-2.5">
                  <span className="text-[34px] font-semibold leading-none" style={{ color }}>
                    {pred.label}
                  </span>
                  <span className="text-[13px] text-white/45">
                    {(pred.failureProbability * 100).toFixed(1)}% failure probability
                  </span>
                </div>
                <p className="mt-1.5 text-[12.5px] text-white/55">
                  This mode uses a stability <em>classifier</em> — it does not return a numeric FoS, so the
                  DGMS {dgms.value.toFixed(1)} ({dgms.material}) threshold cannot be applied directly.
                </p>
              </>
            )}
          </div>

          <div className="flex gap-2">
            <button
              type="button"
              onClick={copy}
              className="rounded-lg border border-white/[0.12] bg-white/[0.05] px-2.5 py-1.5 text-[11.5px] text-white/75 backdrop-blur-md hover:border-white/25 hover:bg-white/[0.09]"
            >
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              type="button"
              onClick={exportReport}
              className="rounded-lg border border-white/[0.12] bg-white/[0.05] px-2.5 py-1.5 text-[11.5px] text-white/75 backdrop-blur-md hover:border-white/25 hover:bg-white/[0.09]"
            >
              Export
            </button>
            <button
              type="button"
              onClick={onRerun}
              className="rounded-lg bg-[#ff9d55]/90 px-2.5 py-1.5 text-[11.5px] font-semibold text-[#231202] hover:bg-[#ffb072]"
            >
              Re-run
            </button>
          </div>
        </div>

        {/* the four detail boxes fill the width as a two-column band;
            stacks when the panel is dragged narrow or below tablet width */}
        <div className={twoCol ? "mt-2.5 grid grid-cols-2 items-start gap-2.5" : "mt-2.5 flex flex-col gap-2.5"}>
          {/* LEFT — method + model accuracy */}
          <div className="flex min-w-0 flex-col gap-2.5">
            <div className="rounded-2xl border border-white/[0.08] bg-white/[0.045] p-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
              <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/45">
                Method
              </h3>
              <Row label="Analysis" value={meta.method} />
              <Row label="Model" value={meta.model} />
              <Row label="Training data" value={meta.data} />
              <Row label="Run at" value={state.at.toLocaleTimeString()} />
            </div>

            <div className="rounded-2xl border border-white/[0.08] bg-white/[0.045] p-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
              <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/45">
                Model Accuracy Detail
              </h3>
              {!metrics ? (
                <p className="text-[12px] text-white/30">Model metrics unavailable.</p>
              ) : isFos ? (
                <>
                  <Row label="Validation R²" value={metrics.metrics.r2?.toFixed(3) ?? "—"} />
                  <Row label="RMSE (test)" value={`±${metrics.metrics.rmse?.toFixed(3)} FoS`} />
                  <Row label="MAE (test)" value={`±${metrics.metrics.mae?.toFixed(3)} FoS`} />
                  {fos != null && metrics.metrics.rmse != null && (
                    <Row
                      label="95% prediction band"
                      value={`${Math.max(0, fos - 1.96 * metrics.metrics.rmse).toFixed(2)} – ${(
                        fos +
                        1.96 * metrics.metrics.rmse
                      ).toFixed(2)}`}
                    />
                  )}
                  <Row label="Held-out cases" value={`${metrics.metrics.n_test} of ${metrics.dataset.rows}`} muted />
                  <p className="mt-1.5 line-clamp-2 text-[10.5px] leading-relaxed text-white/32">
                    {metrics.plain} Band is ±1.96 × validation RMSE.
                  </p>
                </>
              ) : (
                <>
                  <Row label="Validation accuracy" value={`${((metrics.metrics.accuracy ?? 0) * 100).toFixed(0)}%`} />
                  <Row label="ROC-AUC" value={metrics.metrics.roc_auc?.toFixed(3) ?? "—"} />
                  <Row label="This prediction" value={`${(pred.failureProbability * 100).toFixed(1)}% failure prob.`} />
                  <Row label="Held-out cases" value={`${metrics.metrics.n_test} of ${metrics.dataset.rows}`} muted />
                  <p className="mt-1.5 line-clamp-2 text-[10.5px] leading-relaxed text-white/32">{metrics.plain}</p>
                </>
              )}
            </div>
          </div>

          {/* RIGHT — dataset provenance + sensitivity */}
          <div className="flex min-w-0 flex-col gap-2.5">
            <div className="rounded-2xl border border-white/[0.08] bg-white/[0.045] p-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
              <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/45">
                Dataset information
              </h3>
              {!metrics ? (
                <p className="text-[12px] text-white/30">Dataset information unavailable.</p>
              ) : (
                (() => {
                  const d = metrics.dataset;
                  const flags = outOfRange(metrics, state.params);
                  const source =
                    d.source_kind === "mixed"
                      ? `Mixed — ${d.real_pct}% real / ${d.synthetic_pct}% synthetic`
                      : d.source_kind === "real"
                        ? "Real-world field data"
                        : "Synthetic (solver-generated)";
                  return (
                    <>
                      <Row label="Data source" value={source} />
                      <Row label="Training rows" value={d.rows} />
                      <Row label="Input features" value={d.n_features} />
                      <Row
                        label="Within training range"
                        value={
                          flags.length === 0 ? (
                            <span style={{ color: GREEN }}>✓ all inputs in range</span>
                          ) : (
                            <span style={{ color: AMBER }}>⚠ {flags.length} outside</span>
                          )
                        }
                      />
                      {flags.length > 0 && (
                        <div className="mt-1.5 rounded-lg border border-[#ff9f0a]/25 bg-[#ff9f0a]/8 p-2">
                          <p className="text-[10.5px] leading-relaxed text-[#ffcf80]">
                            Extrapolating beyond training data — treat with extra caution:
                          </p>
                          <ul className="mt-1 space-y-0.5">
                            {flags.map((f) => (
                              <li key={f.key} className="text-[10.5px] text-[#ffcf80]/85">
                                {labelFor(mode, f.key)} = {f.value} (trained {f.min}–{f.max})
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      <p className="mt-1.5 line-clamp-3 text-[10.5px] leading-relaxed text-white/32" title={d.provenance}>{d.provenance}</p>
                    </>
                  );
                })()
              )}
            </div>

            <div className="rounded-2xl border border-white/[0.08] bg-white/[0.045] p-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
              <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/45">
                Most influential parameters
              </h3>

              {sens.status === "idle" && (
                <>
                  <p className="mb-2.5 text-[12px] leading-relaxed text-white/45">
                    Measured empirically by re-querying the model once per parameter.
                  </p>
                  <button
                    type="button"
                    onClick={onMeasureSensitivity}
                    className="rounded-lg border border-white/[0.14] bg-white/[0.06] px-3 py-1.5 text-[12px] text-white/85 backdrop-blur-md hover:border-white/28 hover:bg-white/[0.10]"
                  >
                    Measure sensitivity
                  </button>
                  <p className="mt-2 text-[10.5px] text-white/32">
                    {sens.probes} model queries, roughly {sens.etaSec}s.
                  </p>
                </>
              )}

              {sens.status === "running" && (
                <>
                  <p className="mb-2 text-[12px] text-white/55">
                    Probing parameter {sens.done} of {sens.total}…
                  </p>
                  <div className="h-1.5 w-full overflow-hidden rounded-full bg-white/10">
                    <div
                      className="h-full rounded-full bg-[#ff9d55] transition-all duration-300"
                      style={{ width: `${(sens.done / sens.total) * 100}%` }}
                    />
                  </div>
                </>
              )}

              {sens.status === "done" &&
                (sens.items.length === 0 ? (
                  <p className="text-[12px] text-white/30">Sensitivity unavailable.</p>
                ) : (
                  <>
                    {sens.items.map((s) => (
                      <Row
                        key={s.key}
                        label={s.label}
                        value={
                          <span style={{ color: s.direction === "up" ? GREEN : s.direction === "down" ? RED : "#8b8b90" }}>
                            {s.direction === "up" ? "↑ raises" : s.direction === "down" ? "↓ lowers" : "· negligible"}
                          </span>
                        }
                      />
                    ))}
                    <p className="mt-1.5 line-clamp-2 text-[10.5px] leading-relaxed text-white/32">
                      Each parameter nudged by 5% of its range; direction is the model's own response.
                    </p>
                  </>
                ))}
            </div>
          </div>
        </div>

        {/* interpretation — full width across the bottom */}
        <div className="mt-2.5">
          <div className="rounded-2xl border border-white/[0.08] bg-white/[0.045] p-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04)]">
          <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-white/45">
            Interpretation
          </h3>
          <p className="text-[12.5px] leading-relaxed text-white/70">
            {isFos ? (
              passes ? (
                <>
                  The predicted factor of safety of <strong>{fos!.toFixed(2)}</strong> exceeds the DGMS minimum
                  of {dgms.value.toFixed(1)} for {dgms.material} slopes, so this geometry is predicted to be
                  stable under the entered conditions. The margin is{" "}
                  {(((fos! - dgms.value) / dgms.value) * 100).toFixed(0)}% above the threshold.
                </>
              ) : (
                <>
                  The predicted factor of safety of <strong>{fos!.toFixed(2)}</strong> falls below the DGMS
                  minimum of {dgms.value.toFixed(1)} for {dgms.material} slopes. This geometry should be
                  treated as inadequate as entered — flattening the slope, lowering it, or improving drainage
                  are the usual levers.
                </>
              )
            ) : (
              <>
                The model classifies this slope as <strong>{pred.label}</strong> with a{" "}
                {(pred.failureProbability * 100).toFixed(1)}% failure probability. Treat this as a screening
                indicator only; a numeric factor of safety is required for a DGMS compliance assessment.
              </>
            )}
          </p>
          </div>
        </div>
            </div>

      {/* spans the full panel width, beneath both columns */}
      <Disclaimer />
    </div>
  );
}
