"""
wedge_config.py — Slope Stability AI / WedgeFailure
Single source of truth for the wedge FoS regressor, used by
wedge_tabpfn_predict.py.

STATUS: STAGE-1 PRETRAIN ONLY.
Every row of the training CSV is generated by a block-theory
(Hoek & Bray / SWedge) closed-form solver. A model trained on it learns
to reproduce that equation. It is NOT a scientific result and must be
fine-tuned on real field cases before any deployment or publication claim.

FEATURE SET (14): four dips + three slope-relative azimuth differences
+ height, unit weight, and per-joint strength (c, phi) + water.

Rationale for the azimuth treatment: absolute dip directions span 0-360
and carry a wraparound discontinuity (359 deg and 1 deg are 2 deg apart
physically but maximally distant as split values). Measuring each azimuth
against the slope face removes the discontinuity and keeps only the
relative orientation, which is what the mechanics depend on. Differences
are wrapped to (-180, 180] and left SIGNED, so the model retains which
side of the face each joint sits on.
"""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DATA_CSV = PROJECT_ROOT.parent / "Data" / "wedge_synthetic_280.csv"

TARGET = "FoS"

# ---------------------------------------------------------------------
# FEATURES (14) — all derivable from a field survey.
# d_*_slope are computed in load_data(), not present in the CSV.
# ---------------------------------------------------------------------
FEATURES = [
    "dip_j1", "dip_j2",
    "dip_slope", "dip_upper",
    "d_j1_slope", "d_j2_slope", "d_upper_slope",
    "height_m", "gamma_kN_m3",
    "c1_kPa", "phi1_deg",
    "c2_kPa", "phi2_deg",
    "w_pct",
]

DERIVED_FEATURES = {"d_j1_slope", "d_j2_slope", "d_upper_slope"}

# ---------------------------------------------------------------------
# LEAKAGE BLOCKLIST — solver OUTPUTS, never inputs.
# FoS == resisting_kN / driving_kN to ~7e-5 in this file. Verified.
#
# The distinction that matters: inputs to the solver are legitimate
# features; outputs of the solver are not. Volume, areas, weight, N1,
# N2, driving and resisting are all computed AFTER the geometry is
# resolved. weight_kN in particular is the numerator of the driving
# term and is never measured in the field -- it is calculated.
# ---------------------------------------------------------------------
LEAKAGE_COLS = [
    "resisting_kN", "driving_kN", "N1_kN", "N2_kN",
    "weight_kN", "wedge_volume_m3", "area_j1_m2", "area_j2_m2",
    "u_kPa",                                        # from w_pct + geometry
    "psi_i_deg", "alpha_i_deg", "delta_alpha_deg",  # solver intermediates
    "failure_mode", "fos_band",
]


def _wrap180(x):
    """Wrap an angular difference into (-180, 180]."""
    return (x + 180.0) % 360.0 - 180.0


def load_data(verbose=True):
    """Load, assert provenance, derive slope-relative azimuths, return (X, y, df)."""
    import pandas as pd

    df = pd.read_csv(DATA_CSV)

    # --- provenance hard-assert -------------------------------------
    origins = set(df["data_origin"].unique())
    usable = set(df["usable_for_training"].unique())
    assert origins == {"synthetic_blocktheory_solver"}, (
        f"Unexpected data_origin: {origins}. This script is a STAGE-1 "
        "pretrain scaffold and must not be run on mixed or real data."
    )
    assert usable == {"pretrain_only"}, f"Unexpected usable_for_training: {usable}"

    # --- leakage hard-block -----------------------------------------
    bad = [c for c in FEATURES if c in LEAKAGE_COLS]
    assert not bad, f"LEAKAGE: {bad} are solver outputs, not inputs."

    # --- derived slope-relative azimuths ----------------------------
    df["d_j1_slope"]    = _wrap180(df["dipdir_j1"]    - df["dipdir_slope"])
    df["d_j2_slope"]    = _wrap180(df["dipdir_j2"]    - df["dipdir_slope"])
    df["d_upper_slope"] = _wrap180(df["dipdir_upper"] - df["dipdir_slope"])

    missing = [c for c in FEATURES if c not in df.columns]
    assert not missing, f"Missing columns: {missing}"

    X = df[FEATURES].copy()
    y = df[TARGET].copy()

    if verbose:
        print(f"Loaded {len(df)} rows | {len(FEATURES)} features "
              f"({len(DERIVED_FEATURES)} derived)")
        print(f"  origin  : {origins.pop()}")
        print(f"  usable  : pretrain_only")
        print(f"  FoS     : {y.min():.3f} – {y.max():.3f}  (mean {y.mean():.3f})")
    return X, y, df
